---

- name: Drain node
  kubernetes.core.k8s_drain:
          state: uncordon
          name: "{{ ansible_hostname }}"

- name: Wait for cluster to stabilize
  pause:
          minutes: 1
          prompt: "Waiting for cluster to stabilize"

...
