---

- name: Set up containerd.conf
  template:
          src: containerd.conf
          dest: /etc/modules-load.d/containerd.conf
          mode: '644' 
  notify: modprobe

- name: Set up 99-kubernetes-cri.conf
  template:
          src: 99-kubernetes-cri.conf
          dest: /etc/sysctl.d/99-kubernetes-cri.conf
          mode: '644' 
  notify: sysctl
