---
# handlers file for kubernetes
- name: restart_containerd
  service:
          name: containerd
          state: restarted

- name: restart_kubelet
  service:
          name: kubelet
          daemon_reload: yes
          state: restarted

...
