---
- hosts: all
  become: yes
  roles:

        - role: kubernetes_install
          tags: [kubernetes_install]

        - role: kubernetes_init_master
          tags: [kubernetes_init_master]

        - role: kubernetes_init_worker
          tags: [kubernetes_init_worker]

...
